apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    pv: postgres
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data/postgres"