apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    pv: redis
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data/redis"