apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumeClaimTemplates:
        - metadata:
            name: redis-storage
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: redis-storage-class
            resources:
              requests:
                storage: 100Mi
