apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER: "method"
  SPRINGDOC_API_DOCS_ENABLED: "{{ .Values.config.springDocEnabled }}"
  SPRINGDOC_SWAGGER_UI_ENABLED: "{{ .Values.config.springDocEnabled }}"
  SPRING_MAIL_HOST: "{{ .Values.config.mailHost }}"
  SPRING_MAIL_PORT: "{{ .Values.config.mailPort }}"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "name" . }}-postgres-service:5432/{{ .Values.postgres.db }}"
  JWT_EXPIRATION_MS: "{{ .Values.config.jwtExpirationMs }}"
  JWT_REFRESH_EXPIRATION_MS: "{{ .Values.config.jwtRefreshExpirationMs }}"
  JWT_BLACKLIST_TOKENS_SET_NAME: "{{ .Values.config.jwtBlacklistTokensSet }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  CORS_ALLOWED_METHODS: "{{ .Values.config.corsAllowedMethods }}"
  CORS_ALLOWED_HEADERS: "{{ .Values.config.corsAllowedHeaders }}"
  CORS_ALLOW_CREDENTIALS: "{{ .Values.config.corsAllowCredentials }}"
  SPRING_REDIS_HOST: "{{ include "name" . }}-{{ .Values.config.redisHost }}"
  SPRING_REDIS_PORT: "{{ .Values.config.redisPort }}"
