apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
spec:
  rules:
    - host: "{{ .Values.spring.ingressHost }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-nodeport-service
                port:
                  number: {{ .Values.spring.nodePort }}
